vich_uploader:
    db_driver: orm

    mappings:
        tweets:
            uri_prefix: /images/tweets
            upload_destination: '%kernel.project_dir%/public/images/tweets'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true